<a href="https://colab.research.google.com/github/snehavyshnavi/Deep-Learning/blob/main/DL_program14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
words = ["the", "cat", "sat", "on", "the", "mat"]
vocab = sorted(set(words))
print("Vocabulary:", vocab)
word_to_index = {word: i for i, word in enumerate(vocab)}
print("\nWord to Index Mapping:", word_to_index)
num_words = len(words)
vocab_size = len(vocab)
one_hot_matrix = np.zeros((num_words, vocab_size), dtype=int)

for i, word in enumerate(words):
  index = word_to_index[word]
  one_hot_matrix[i, index] = 1
print("\nOne-Hot Encoded Matrix:")
print(one_hot_matrix)

Vocabulary: ['cat', 'mat', 'on', 'sat', 'the']

Word to Index Mapping: {'cat': 0, 'mat': 1, 'on': 2, 'sat': 3, 'the': 4}

One-Hot Encoded Matrix:
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]]


In [ ]:
print("\nOne-Hot Encoded Matrix:")
print(one_hot_matrix)


One-Hot Encoded Matrix:
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]]


In [ ]:
for i, word in enumerate(words):
  print(f"{word:>5} {one_hot_matrix[i]}")

  the [0 0 0 0 1]
  cat [1 0 0 0 0]
  sat [0 0 0 1 0]
   on [0 0 1 0 0]
  the [0 0 0 0 1]
  mat [0 1 0 0 0]


In [ ]:
import numpy as np

text = "hello"

chars = sorted(set(text))
print("Character:", chars)

Character: ['e', 'h', 'l', 'o']


In [ ]:
char_to_index = {ch: i for i, ch in enumerate(chars)}
print("Character to Index Mapping:", char_to_index)

Character to Index Mapping: {'e': 0, 'h': 1, 'l': 2, 'o': 3}


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
vocab_size = 10000
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words = vocab_size)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
print("Training samples:", len(x_train))
print("Test samples:", len(x_test))
print("Example review (as integers):", x_train[0][:10])

Training samples: 25000
Test samples: 25000
Example review (as integers): [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65]


In [ ]:
maxlen = 200
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen = maxlen)
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen = maxlen)

print("Shape of x_train:", x_train.shape)
print("Shape of x_test:", x_test.shape)

Shape of x_train: (25000, 200)
Shape of x_test: (25000, 200)


In [ ]:
model = keras.Sequential([
    layers.Embedding(input_dim=vocab_size, output_dim=16, input_length=maxlen),
    layers.GlobalAveragePooling1D(),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ ?                      │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=5, batch_size=512, validation_split=0.2, verbose=1)

Epoch 1/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.5237 - loss: 0.6901 - val_accuracy: 0.6422 - val_loss: 0.6746
Epoch 2/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.6340 - loss: 0.6674 - val_accuracy: 0.7448 - val_loss: 0.6406
Epoch 3/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7309 - loss: 0.6275 - val_accuracy: 0.7522 - val_loss: 0.5890
Epoch 4/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7761 - loss: 0.5688 - val_accuracy: 0.8194 - val_loss: 0.5323
Epoch 5/5
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8274 - loss: 0.5130 - val_accuracy: 0.8420 - val_loss: 0.4775


In [ ]:
results = model.evaluate(x_test, y_test, verbose=2)
print("\nTest Accuracy:", results[1])

782/782 - 2s - 2ms/step - accuracy: 0.8363 - loss: 0.4820

Test Accuracy: 0.8363199830055237


In [ ]:
embedding_layer = model.layers[0]
embeddings = embedding_layer.get_weights()[0]
print("\nEmbedding matrix shape:", embeddings.shape)


Embedding matrix shape: (10000, 16)
